# Generated by Django 4.1 on 2022-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(
                default="Dymasius: Tech, Biz, Social!", max_length=255
            ),
        ),
    ]
