# Generated by Django 4.1 on 2022-09-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0004_category_post_catagory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="catagory", new_name="category",
        ),
    ]
